"""
Visualize the ATS LangGraph workflow structure.
This script generates a visual representation of the graph.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


def visualize_graph():
    print("Creating ATS Graph visualization...\n")

    print("="*80)
    print("ATS SYSTEM - LANGGRAPH WORKFLOW")
    print("="*80)
    print()
    print("Graph Structure:")
    print()
    print("  START")
    print("    |")
    print("    +--> [1] Parse Resume")
    print("    |     +-> Extract text from PDF/DOCX/TXT")
    print("    |     +-> Convert to structured data")
    print("    |")
    print("    +--> [2] Parse Job Description")
    print("    |     +-> Extract requirements")
    print("    |     +-> Identify must-have vs nice-to-have skills")
    print("    |")
    print("    +--> [3] Analyze Resume")
    print("    |     +-> Resume Analysis Agent")
    print("    |     +-> Extract key qualifications")
    print("    |     +-> Identify strengths and weaknesses")
    print("    |")
    print("    +--> [4] Analyze Job")
    print("    |     +-> Job Analysis Agent")
    print("    |     +-> Prioritize requirements")
    print("    |     +-> Identify deal-breakers")
    print("    |")
    print("    +--> [5] Calculate Match Score")
    print("    |     +-> Matching Agent")
    print("    |     +-> Multi-dimensional scoring")
    print("    |     +-> Gap analysis")
    print("    |")
    print("    +--> [6] Generate Recommendation")
    print("    |     +-> Recommendation Agent")
    print("    |     +-> Hire/No-hire decision")
    print("    |     +-> Interview questions")
    print("    |")
    print("    +--> [7] Compile Final Evaluation")
    print("          +-> Aggregate all results")
    print("          +-> Generate comprehensive report")
    print("    |")
    print("   END")
    print()
    print("="*80)
    print()

    print("State Flow:")
    print()
    print("  Initial State:")
    print("    - resume_file_path")
    print("    - job_description")
    print("    - job_id")
    print()
    print("  Intermediate States:")
    print("    - parsed_resume")
    print("    - parsed_job")
    print("    - resume_analysis")
    print("    - job_analysis")
    print("    - match_score")
    print("    - gap_analysis")
    print("    - recommendation")
    print("    - interview_questions")
    print()
    print("  Final State:")
    print("    - final_evaluation (complete assessment)")
    print()
    print("="*80)
    print()

    print("Agent Capabilities:")
    print()
    print("  1. Resume Analysis Agent:")
    print("     - Career level assessment")
    print("     - Key qualifications extraction")
    print("     - Strengths and weaknesses identification")
    print()
    print("  2. Job Analysis Agent:")
    print("     - Requirement prioritization")
    print("     - Deal-breaker identification")
    print("     - Seniority level determination")
    print()
    print("  3. Matching Agent:")
    print("     - Multi-dimensional scoring:")
    print("       • Skills match (0-100)")
    print("       • Experience match (0-100)")
    print("       • Education match (0-100)")
    print("       • Overall score (0-100)")
    print("     - Gap analysis and recommendations")
    print()
    print("  4. Recommendation Agent:")
    print("     - Decision: strong_yes/yes/maybe/no/strong_no")
    print("     - Confidence level: high/medium/low")
    print("     - Detailed reasoning")
    print("     - Tailored interview questions")
    print()
    print("="*80)

    print("\nGraph compiled successfully!")
    print("Use this workflow to evaluate candidates automatically.\n")


if __name__ == "__main__":
    visualize_graph()
