"""
Visualize the Advanced ATS LangGraph workflow structure.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


def visualize_advanced_graph():
    print("="*80)
    print("ADVANCED ATS SYSTEM - LANGGRAPH WORKFLOW")
    print("="*80)
    print()
    print("Graph Structure:")
    print()
    print("  START")
    print("    |")
    print("    +-> [1] Parse Resume")
    print("    |     +-> Extract text from PDF/DOCX/TXT")
    print("    |     +-> Convert to structured data")
    print("    |     +-> Store candidate in Memgraph")
    print("    |")
    print("    +-> [2] Parse Job Description")
    print("    |     +-> Extract requirements and details")
    print("    |     +-> Store job in Memgraph")
    print("    |")
    print("    +-> [3] Classify Requirements")
    print("    |     +-> MUST_HAVE: Truly critical")
    print("    |     +-> NICE_TO_HAVE: Explicitly optional")
    print("    |     +-> DISGUISED_NICE_TO_HAVE: Inflated requirements")
    print("    |     +-> Detect contradictions (junior role + senior req)")
    print("    |     +-> Store requirements in Memgraph")
    print("    |")
    print("    +-> [4] Evidence Matching")
    print("    |     +-> Semantic search (not just keywords)")
    print("    |     +-> Find implicit demonstrations")
    print("    |     +-> Example: 'mentored juniors' -> leadership")
    print("    |     +-> Cross-reference evidence (detect over-claiming)")
    print("    |     +-> Store evidence in Memgraph")
    print("    |")
    print("    +-> [5] Gap Analysis")
    print("    |     +-> Categorize gaps: critical/significant/bridgeable")
    print("    |     +-> Determine if explanation needed")
    print("    |     +-> Generate explanation questions")
    print("    |")
    print("    +-> [5a] Generate Explanation Request (if needed)")
    print("    |     +-> Personalized email to candidate")
    print("    |     +-> Ask about specific gaps")
    print("    |     +-> Non-judgmental, clarifying tone")
    print("    |")
    print("    +-> [6] Bias Audit")
    print("    |     +-> Audit model's OWN reasoning")
    print("    |     +-> Detect age proxies (graduation year)")
    print("    |     +-> Detect gender proxies (career gaps)")
    print("    |     +-> Detect name bias (ethnic names)")
    print("    |     +-> Detect education prestige bias")
    print("    |     +-> Calculate fairness score")
    print("    |     +-> Store bias flags in Memgraph")
    print("    |")
    print("    +-> [7] Calculate Match Score")
    print("    |     +-> Evidence-weighted scoring")
    print("    |     +-> Credibility-adjusted")
    print("    |     +-> Multi-dimensional (skills/exp/edu)")
    print("    |")
    print("    +-> [8] Generate Recommendation")
    print("    |     +-> Hire/No-hire with confidence")
    print("    |     +-> Detailed reasoning")
    print("    |     +-> Interview questions")
    print("    |")
    print("    +-> [9] Determine Human Review Need")
    print("    |     +-> Check triggers:")
    print("    |     |   * Borderline score (45-65)")
    print("    |     |   * Bias detected")
    print("    |     |   * Critical gaps")
    print("    |     |   * Low confidence")
    print("    |     +-> Prepare review package if needed")
    print("    |")
    print("    +-> [10] Human Review (conditional)")
    print("    |     +-> Executive summary")
    print("    |     +-> Key questions")
    print("    |     +-> Relevant excerpts")
    print("    |     +-> Bias warnings")
    print("    |     +-> Await human decision")
    print("    |")
    print("    +-> [11] Compile Final Evaluation")
    print("          +-> Aggregate all results")
    print("          +-> Store in Memgraph")
    print("          +-> Generate report")
    print("    |")
    print("   END")
    print()
    print("="*80)
    print()

    print("Conditional Routing:")
    print()
    print("  After Gap Analysis:")
    print("    IF critical gaps need explanation")
    print("      -> Generate Explanation Request")
    print("    ELSE")
    print("      -> Skip to Bias Audit")
    print()
    print("  After Human Review Check:")
    print("    IF needs_human_review == True")
    print("      -> Pause for Human Review")
    print("    ELSE")
    print("      -> Skip to Compile")
    print()
    print("="*80)
    print()

    print("State Evolution:")
    print()
    print("  Initial:")
    print("    - resume_file_path")
    print("    - job_description")
    print("    - job_id")
    print()
    print("  After Parsing:")
    print("    + parsed_resume")
    print("    + parsed_job")
    print()
    print("  After Classification:")
    print("    + classified_requirements (with types)")
    print("    + requirement_contradictions")
    print()
    print("  After Evidence Matching:")
    print("    + evidence_results (per requirement)")
    print("    + evidence_credibility")
    print("    + over_claimed_evidence")
    print()
    print("  After Gap Analysis:")
    print("    + gap_analysis")
    print("    + requires_explanation (boolean)")
    print("    + explanation_generated (if needed)")
    print()
    print("  After Bias Audit:")
    print("    + bias_audit")
    print("    + implicit_bias_patterns")
    print("    + fairness_score")
    print()
    print("  After Scoring:")
    print("    + match_score")
    print("    + recommendation")
    print()
    print("  After Human Review Check:")
    print("    + needs_human_review (boolean)")
    print("    + review_package (if needed)")
    print("    + human_decision (if reviewed)")
    print()
    print("  Final:")
    print("    + final_evaluation (complete)")
    print("    + evaluation_id")
    print()
    print("="*80)
    print()

    print("Key Differentiators:")
    print()
    print("  1. REQUIREMENT CLASSIFICATION")
    print("     - Detects when 'required' doesn't mean required")
    print("     - Example: '5+ years' may accept 3 years")
    print()
    print("  2. EVIDENCE-BASED MATCHING")
    print("     - Semantic understanding > keywords")
    print("     - 'Built tool used by 50 people' = leadership")
    print()
    print("  3. CONTEXTUAL GAP ANALYSIS")
    print("     - Career breaks, pivots, learning paths")
    print("     - Requests explanations vs auto-reject")
    print()
    print("  4. BIAS SELF-AUDIT")
    print("     - Model audits ITS OWN reasoning")
    print("     - Flags age/gender/name/prestige proxies")
    print()
    print("  5. HUMAN-IN-THE-LOOP")
    print("     - Smart routing for borderline cases")
    print("     - Comprehensive review package")
    print()
    print("  6. FEEDBACK LOOP")
    print("     - Tracks human vs model disagreements")
    print("     - Drift analysis for model improvement")
    print()
    print("="*80)
    print()

    print("Database Integration (Memgraph):")
    print()
    print("  Nodes:")
    print("    - Candidate, Job, Requirement")
    print("    - Evaluation, Evidence, BiasFlag")
    print("    - Feedback")
    print()
    print("  Relationships:")
    print("    - (Candidate)-[:EVALUATED_FOR]->(Evaluation)")
    print("    - (Evaluation)-[:FOR_JOB]->(Job)")
    print("    - (Job)-[:HAS_REQUIREMENT]->(Requirement)")
    print("    - (Evaluation)-[:HAS_EVIDENCE]->(Evidence)")
    print("    - (Evidence)-[:ADDRESSES]->(Requirement)")
    print("    - (Evaluation)-[:HAS_BIAS_FLAG]->(BiasFlag)")
    print("    - (Evaluation)-[:HAS_FEEDBACK]->(Feedback)")
    print()
    print("  Analytics Queries:")
    print("    - Drift analysis (model vs human decisions)")
    print("    - Bias pattern detection")
    print("    - Requirement flexibility trends")
    print()
    print("="*80)


if __name__ == "__main__":
    visualize_advanced_graph()
